spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://smallface-db.cnbmetcseemr.eu-central-1.rds.amazonaws.com/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate.ddl-auto: update
